version: '3.1'

services:
  dvwa:
    image: 'vulnerables/web-dvwa'
    hostname: 'dvwa'
    ports:
      - '1000:80'
    restart: always
  webgoat:
    image: 'webgoat/webgoat-8.0'
    hostname: 'webgoat'
    ports:
      - '1001:8080'
    restart: always
  juiceshop:
    image: 'bkimminich/juice-shop'
    hostname: 'juiceshop'
    ports:
      - '1002:3000'
    restart: always
