version: '3.1'

services:
  dvwa:
    image: 'vulnerables/web-dvwa'
    hostname: 'dvwa'
    ports:
      - '1000:80'
    restart: always
  gruyere:
    image: 'karthequian/gruyere:latest'
    hostname: 'gruyere'
    ports:
      - '8008:8008'
    restart: always
  mutillidale:
    image: 'citizenstig/nowasp'
    hostname: 'mutillidale'
    ports:
      - '80:80'
      - '3306:3306'
    enviroment:
      MYSQL_PASS: 'Chang3ME!'
    restart: always
  goatandwolf:
    image: 'webgoat/goatandwolf'
    hostname: 'goatandwolf'
    ports:
      - '1001:8080'
      - '1002:9090'
    restart: always
  juiceshop:
    image: 'bkimminich/juice-shop'
    hostname: 'juiceshop'
    ports:
      - '1003:3000'
    restart: always
  pixidb:
    image: deadrobots/pixi:datastore
    container_name: pixidb
    ports:
      - '27017:27017'
      - '28017:28017'
    restart: always  
  pixiapp:
    image: deadrobots/pixi:app
    ports:
      - '8000:8000'
      - '8090:8090'
    restart: always
